# Generated by Django 3.1.13 on 2021-09-14 22:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cms', '0022_auto_20180620_1551'),
        ('djangocms_table', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='cmsplugin_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, related_name='djangocms_table_table', serialize=False, to='cms.cmsplugin'),
        ),
        migrations.AlterField(
            model_name='table',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256, verbose_name='name'),
        ),
    ]
